### PR TITLE
[#140] Fixed parsing request body when path expression points to a si…

### PR DESCRIPTION
**Pull request by mbilinainteca**
…ngle item instead of multiple items.

### CODE REVIEW

**Comment by mhewedy** [comment]
I can see tests are failing ... are this related to the change?

**Comment by mbilinainteca** [comment]
I can't see which tests are failing. How to check it?

**Comment by mhewedy** [comment]
Check the ci here: https://travis-ci.org/castlemock/castlemock/builds/594636819?utm_source=github_status&utm_medium=notification

**Comment by karldahlgren** [comment]
Hi @mbilinainteca.
The problem here is most likely not due to @mbilinainteca commit. From what I can see, Travis CI seems to not support Oracle JDK 8 and 9. I working on some reconstructions right now for the project and will resolve this issue at the same time.

I will take a look at your contribution as soon as I can.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi again @mbilinainteca.
Just took a quick look. The commit looks great! I can merge your pull request as soon as the contribution license has been signed. All you need to do is to sign the following license contribution agreement and send it to us: https://www.apache.org/licenses/icla.pdf

Once this is done, we can merge your request.

Thank you very much!
Best regards,
Karl Dahlgren

**Pull request merged**
