### PR TITLE
add query string support

### PR DESCRIPTION
**Pull request by saiello**
Hi @karldahlgren this may help with query strings. #63

### CODE REVIEW

**Comment by karldahlgren** [comment]
Hi @saiello.
Thank you so much for your contribution. It is really appreciated!
It is required to sign a CLA before we accept any pull request. Right now we are using the Apache CLA.
Would it be possible for you to sign it and send me the following document: https://www.apache.org/licenses/icla.pdf

Apache CLA: https://www.apache.org/licenses/icla.pdf
Mail: [karl.dahlgren@castlemock.com](mailto:karl.dahlgren@castlemock.com) 

Thank you once again for your contribution and understanding.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @saiello.
Thank you once again for your contribution! Much appreciated. I took a look at the commit and it looks correct. However, I'm not certain this is the approach we should take on this. I'm thinking that it might be better to support this by adding another response strategy instead. The benefit with that would be that you, as a user, could use pattern matching and you could also configure a default response that would be use if no mocked response would match. Would do you think? If we would go that path instead, there are code in your commit that we could absolutely reuse.

Best regards,
Karl Dahlgren

**Comment by saiello** [comment]
Hi @karldahlgren, this pull request allow the user to specify query parameters in uri and use them in query response strategy together with pathParameters. 

I wrote this for a personal need: serve different responses based on query parameters.
Do you have a different idea to solve the problem?

**Comment by karldahlgren** [comment]
Hi @saiello.
Yes, I think we could do it another way. We could have the following response strategies:

- Parameter match
- Query String match
- Parameter and Query String match

Then you could specify exactly which response you would like to have based on regex, exact matching or any matching. I believe that would be the most flexible approach. What do you think?

**Comment by saiello** [comment]
IMHO adding three different strategy for query matching is not the right way.

You should already have this flexibility.  In your above strategy list, the first two are redundant. We actually have implemented the third and a user can obtain others just by specifying the "Match any" for all parameters he doesn't want to use for selection. 

Suppose having `/sample/{foo}/{bar}/?id={id}`

Only Query Params
---
- foo = any
- bar = any 
- id = 1

Only Path Params
---
- foo = 'aaa'
- bar = 'bbb'
- id = any

Both Path and Query Params
---
- foo = 'aaa'
- bar = 'bbb'
- id = 1


Rather, I would strive to mix Query and JsonPath/Xpath matching. 

Let me know If i'm wrong. I have to admit that I start using Castlemock 3 days ago 😄

**Comment by karldahlgren** [comment]
Haha, you are absolutely right. I'm an idiot! 😅
I played around with it and think it works exactly the way you describe it and the way it should work. Most have gotten it totally confused. Sorry for all the confusion.

Once again, thank you for the contribution. I hope you will continue contributing and correcting me when I'm lost and confused 😂 

Oh, btw: Do you want me to add you to the list of authors? The list of authors will be listed here on Github and also be part with each release.

Best regards,
Karl Dahlgren

**Comment by saiello** [comment]
LoL. Yes, add me to the authors. why not!?
I also noticed a little bug on resource bulk updated. I will try to figure out how to fix it.

**Comment by Keldragolo** [comment]
I have a rest that post '{"name":"John"}' should query string be able to extract John ? Or is purely for get?

**Comment by karldahlgren** [comment]
Hi @Keldragolo. 
This one is for matching URL parameters or queries. I believe that the one you are looking for is JSON Path mapping. You can find information about it here: https://github.com/castlemock/castlemock/wiki/JSON-Path

I hope this helps you.
Best regards,
Karl Dahlgren

**Comment by Keldragolo** [comment]
Karl

The response are predefined, I would like to return a response with the
value passed in body. Similar to query string and parameter but from body.

The JSON path takes the passed in value lookup something and return
predefined value.

Regards

Alex

**Comment by karldahlgren** [comment]
@Keldragolo.
Unfortunately, there isn't any support for this today. However, we might be able to add this in the future as an expression. Would this be interesting for you? Do you want me to create a ticket for this?

Best regards,
Karl Dahlgren

**Comment by Keldragolo** [comment]
Karl

This feature would be useful.

Please create a ticket.

Thanks.

Alex

**Comment by karldahlgren** [comment]
Hi @Keldragolo.
Your requested feature has now been implemented and will be part of the next release. The next release is expected to be released at the end of this week. Please see the wiki expression session for further information. If you have any feedback or suggestions on how we can improve it even further, please don't hesitate to create a ticket =).

Thanks,
Best regards,
Karl Dahlgren

**Comment by Keldragolo** [comment]
Karl

Excellent.

End of this week meaning tomorrow?

Will this work with SOAP as well or only REST?

Thanks.

Alex

**Comment by karldahlgren** [comment]
Hi @Keldragolo.
This will only works with REST since it is JSON and SOAP requests are always in XML.

Best regards,
Karl Dahlgren

**Comment by Keldragolo** [comment]
Karl

I can see the logs are kept for all post and get.  Is this information
stored in database and can this be accessible?

Regards

Alex

**Comment by karldahlgren** [comment]
@Keldragolo.
The request and response logs are written down to file (Like everything else Castle Mock stores) and can be accessible by either opening these files or view them from Castle Mock (Under the logs session).

The files generated by Castle Mock are stored on the user account root and then under /.castlemock

Best regards,
Karl Dahlgren

**Comment by Keldragolo** [comment]
Karl

Is the new feature part of Query String expression?

Regards

Alex

**Comment by karldahlgren** [comment]
Hi @Keldragolo.
It is a new expression similar to the query string expression. You can find more information about it on our wiki: https://github.com/castlemock/castlemock/wiki/Expression#body-json-path

Best regards,
Karl Dahlgren

**Comment by Keldragolo** [comment]
Karl

Is version 1.36 with the added feature?

For upgrade do you replace the WAR only.

Alex

**Comment by karldahlgren** [comment]
@Keldragolo 
The feature was added two days ago and is part of the release that was released yesterday (v1.38). To upgrade, you simply need to download and replace the war file.

We can continue this conversation over email instead of this pull request. Please send me an email to karl.dahlgren@castlemock.com if you have further questions.

Best regards,
Karl Dahlgren

**Pull request merged**
