### PR TITLE
new RestResponseStrategy used to read headers from JSON request

### PR DESCRIPTION
**Pull request by leandrocharlier**
JsonPath now detects headers from JSON Request

### CODE REVIEW

**Comment by karldahlgren** [comment]
Hi @leandrocharlier.
Thank you so much for your pull request. I started to take a look at it, but I'm curious about the use case. Would you mind to giving me the background and a scenario?

Thank you =)
Best regards,
Karl Dahlgren

**Comment by leandrocharlier** [comment]
Thank you for your prompt reply, this change appeared from a need that I had while I was using castlemock in my work.
 
The point is for certain services such as one called "CutPoint" (which returns if an operation is available), the type of operation is sent in the json header, for example: OperationType: "PAY_CARD", so, this REST service returns if that operation is available or not. Using castlemock the problem was that I could not change the REST service’s responses depend on the json’s header, I could only have a logic when parameters come in the same query and due to that limitation I decided to make that change.
Sorry for my English.
Thank you!
Keep in touch,
Leandro Charlier.

**Comment by karldahlgren** [comment]
Hi @leandrocharlier.
Thank you for clarifying. Understand it better. However, I'm not certain that is the right way of doing this. Isn't there a risk that the JSON expression could work on both the body and headers? Can't that lead to unexpected behavior? For example, the test query:
`$.[?(@.connection == 'keep-alive')]`
could be used for both the header and the body.
I would suggest another approach: Add new RestResponseStrategy type, HEADER_MATCH. In that case, we could just simply match the header instead. 

I think your commit looks really good, but I'm worried that it could lead to unexpected behavior.
What do you think?
Would the other approach work for you?

Best regards,
Karl Dahlgren

**Comment by leandrocharlier** [comment]
Hi @karldahlgren.
You're right! I was doing tests and the JSON expression worked in the body and the headers, after that I started to develop the new RestResponseStrategy "Header match" and I think it's already finished. I put the header match format like this: "Key -> Value". 
When you can, please take a look to see if everything is correct, any changes that this needs, please let me know.
Pull request name changed to "new RestResponseStrategy used to read headers from JSON request"
I wait for your answer!
 
Regards.
Leandro Charlier

**Comment by karldahlgren** [comment]
Hi @leandrocharlier.
Thank you so much for your contribution. It looks really great! Good work!
The only thing that is required before we can pull this request is for you to sign the Apache contributor license agreement and send to us: https://www.apache.org/licenses/icla.pdf

Once it has been signed and we have received it, we will include your changes and prepare a new release. Once again, great work!

Thank you
Best regards
Karl Dahlgren

**Comment by leandrocharlier** [comment]
Hi @karldahlgren.
I have already sent the Apache contributor license agreement to karl@dahlgren.info.
Thanks for being so cool and for the positive feedback!

Thank you!
Regards.
Leandro Charlier.

**Comment by karldahlgren** [comment]
Thank you @leandrocharlier!
Really great work! Will merge this right away. I will prepare a new release at the end of the week.
Do you want to be listed as author in the author list (https://github.com/castlemock/castlemock/blob/master/AUTHORS)? =)

Best regards, 
Karl Dahlgren

**Comment by leandrocharlier** [comment]
Hi @karldahlgren. 
Yes, I would like to be on the list of authors, thank you very much for everything!

Best regards,
Leandro Charlier

**Pull request merged**
