### PR TITLE
fix (SOAP 1.1): put message name as a operation identifier

### PR DESCRIPTION
**Pull request by harpipl**
1. Few weaks ago I tried to use Castle Mock and I had a problem with value of operation identifier. Now I fixed it and it works. The identifier should be taken from message name.

2. I know gradle just a little but I additionally added: archivesBaseName = "${it.group}-${it.name}" to file build.gradle and now under Windows I can build correctly castlemock.war.
I don't know how to do this without this line.

### CODE REVIEW

**Comment by karldahlgren** [comment]
HI @harpipl.
Thank you so much for your contribution. I've only looked at it briefly and it looks very good. 
All Castle Mock contributors are required to sign the Apache CLA before their commits can be merged into the codebase. Would it be possible for you to sign and send me the following document: [https://www.apache.org/licenses/icla.pdf](https://www.apache.org/licenses/icla.pdf)

Apache CLA: https://www.apache.org/licenses/icla.pdf
Mail: karl.dahlgren@castlemock.com

Once the document has been signed, I will merge your contribution. Would you like me to add you to the list of authors as well?

I apologies if this is inconvenient, but it is very much appreciated. 
Thank you once again.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Hi @harpipl.
Sorry to bother you, but do you have an update on my previous questions?

Thanks!
Best regards,
Karl Dahlgren

**Comment by harpipl** [comment]
Hi,

Sorry but I forgotten!

I attached two pages. Is it ok?
And you can add me to the list of authors.

Thanks!
Arkadiusz Adamczak

niedz., 17 cze 2018 o 13:11 Karl Dahlgren <notifications@github.com>
napisał(a):

**Comment by karldahlgren** [comment]
Hi @harpipl.
No problem at all.
Unfortunately, I can't find your attachment. Would you mind sending them to my email?

Email: karl.dahlgren@castlemock.com

Thank you very much!
Best regards,
Karl Dahlgren

**Comment by harpipl** [comment]
Hi,

Last time I attached two files: ICLA - page1.jpg and ICLA - page2.jpg.
Ok, now I also attache this two files.

Best regards,
Arkadiusz Adamczak

niedz., 17 cze 2018 o 18:21 Karl Dahlgren <notifications@github.com>
napisał(a):

**Comment by karldahlgren** [comment]
Hi @harpipl.
Are you adding the files as an attachment when responding to the email notification? Because they are not present in the pull request conversation. I can't find them anywhere. Nor can I find them as an attachment in the GitHub notification email. If you haven't done this already, could you please go to Github and then add the files as attachments to the pull request conversation?

Thanks.
Best regards,
Karl Dahlgren

**Comment by harpipl** [comment]
Hi!

I did it and added them on Github to the pull request conversation.
Please check it and write me if all is ok.

Best regards,
Arkadiusz Adamczak

niedz., 17 cze 2018 o 20:09 Karl Dahlgren <notifications@github.com>
napisał(a):

**Comment by karldahlgren** [comment]
Hi @harpipl.
Still unable to see the attached files. According to GitHub, you are responding to the conversation with email. You have to log into GitHub and attach the files by dragging or dropping them into the comment textarea.

Best regards,
Karl Dahlgren

**Comment by harpipl** [comment]
icla - page1
icla - page2

**Comment by harpipl** [comment]
Hi!

Sorry for my mistake.
Please verify now. Now should be ok.

Best regards,
Arkadiusz Adamczak

niedz., 17 cze 2018 o 22:51 Karl Dahlgren <notifications@github.com>
napisał(a):

**Pull request merged**
